import React from "react";

function About() {


    return (
        <div>
            <h1>Who are we?</h1>
            <p>We are creators who are passionate about building software products that helps people to find solutions in the easiest way possible</p>
            <h1>Why did we create www.makingalbum.com?</h1>
            <p>We have seen people complaining that often times, they loose thier precious pictures from their phone/memory card/hard disk. To put an end to this, we decided to create </p>
            <p>a free and simple software product which can turn all your pictures into a photo album collage that is 'ready to be printed'. By this way you can save the time in curating the pictures </p>
            <p>The only effort you would need to take is print the pdf photo album (generated by you from the website) and bind them. </p>
            <h2>Now, you have your memories treasured for a lifetime !</h2>
        </div>
    )
}

export default About;