import React from "react";

function About() {


    return (
        <div>
            <h1>Who are we?</h1>
            <p>We are creators who are passionate about building software products that helps people to find solutions in the easiest way possible</p>
            <h1>Why did we create www.makingalbum.com?</h1>
            <p>We have seen people complaining that often times, they loose thier precious pictures from their phone/memory card/hard disk. To put an end to this, we decided to create </p>
            <p>a free and simple software product which can turn all your pictures into a photo album collage that is 'ready to be printed'. By this way you can save the time in curating the pictures </p>
            <p>The only effort you would need to take is print the pdf photo album (generated by you from the website) and bind them. </p>
            <h2>Now, you have your memories treasured for a lifetime !</h2>
            <embed src={'https://cx-file-inputs-outputs.s3.amazonaws.com/ad3a0a9a-1f54-4bbf-aea5-8d8298fa9259.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAZSOQQKP3NYMVLFYA%2F20220511%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20220511T172551Z&X-Amz-Expires=6000&X-Amz-SignedHeaders=host&X-Amz-Signature=65cf9b7ba48cb329736f48b1bc7b016a28ab835fb50697278168d8d3cd956746'} type="application/pdf"/>
        </div>
    )
}

export default About;